### ISSUE TITLE
Is it possible to use naturalsorter in Jekyll?

### ISSUE THREAD

**Issue by kimbaudi** [versioneye/naturalsorter#11]
Is it possible to use naturalsorter for my Jekyll blog?

I added the following to my Gemfile

`gem 'naturalsorter', '3.0.15'`

And I run `bundle install`

Is it possible to sort by `site.categories`

Currently I'm using built-in sort:

```
      {% assign sorted_categories = site.categories | sort %}
      {% for category in sorted_categories %}
      <h2 class="title is-4">{{ category[0] }}</h2>
      {% endfor %}
```

How can I use this to naturally sort `site.categories` in Jekyll (if possible)?

**Comment by reiz** [comment]
Hi @kimbaudi. If you have an Array of objects you can use this here: 

```
Naturalsorter::Sorter.sort_version_by_method(array, method, asc = true )
```

I don't know how the objects look like in `site.categories`. But if every object in `site.categories` has a public attribute `name` it would be: 

```
Naturalsorter::Sorter.sort_version_by_method(site.categories, 'name', asc = true )
```

Let me know if that works for you.

**Comment by kimbaudi** [comment]
closing this issue. natural sorting has been added a while back.
