### ISSUE TITLE
Support for release dates

### ISSUE THREAD

**Issue by reiz** [versioneye/naturalsorter#12]
If a release date / time is available that should be used to sort the versions.

**Comment by ylecuyer** [comment]
It seems that changing the timestamp function here:  https://github.com/versioneye/naturalsorter/blob/master/lib/versioncmp.rb#L225

with a length of 9 solve the issue and no tests are failing.

A timestamp of 8 digit (max: 9999999) would be max 3/3/1973 10:46:39 which is unlikely to happen in a version number
