### ISSUE TITLE
Fix Maven artifacts version sorting

### ISSUE THREAD

**Issue by jcarsique** [versioneye/naturalsorter#9]
Hi, 

The version ordering is wrong on https://www.versioneye.com/java/org.apache.poi:poi . For instance, 3.10 is greater than 3.9.
Current sorting:

    3.9 (Dec 06, 2012) 
    3.8 (Apr 01, 2012) 
    3.7 (Jan 05, 2012) 
    3.6 (Jan 05, 2012) 
    3.10-beta2 (Sep 23, 2013) 
    3.10-beta1 (Aug 10, 2013) 
    3.8-beta5 (Jan 05, 2012) 
    (...)
    3.8-beta1 (Jan 05, 2012) 
    3.7-beta3 (Jan 05, 2012) 
    3.7-beta2 (Jan 05, 2012) 
    3.7-beta1 (Jan 05, 2012) 
    3.5-beta6 (Jan 05, 2012) 
    (...)
    3.5-beta1 (Jan 05, 2012) 
    3.1-beta2 (Jan 05, 2012) 
    3.1-beta1 (Jan 05, 2012) 
    3.0.2-beta2 (Jan 05, 2012) 
    3.0.2-beta1 (Jan 05, 2012) 
    3.0.2-FINAL (Jan 05, 2012) 
    3.0.1-FINAL (Jan 05, 2012) 
    3.10-FINAL (Feb 16, 2014) 
    3.5-FINAL (Jan 05, 2012) 
    3.2-FINAL (Jan 05, 2012) 
    3.1-FINAL (Jan 05, 2012) 
    3.0-FINAL (Jan 05, 2012)

**Comment by reiz** [comment]
I did some improvements yesterday. It should be fine now. Please double check it. If it's still not like expected feel free to reopen this ticket.
